
variables:
  DOCKER_CACHE_IMAGE: $CI_REGISTRY_IMAGE/cache
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:${CI_PIPELINE_ID}

stages:
  - lint_dockerfile
  - build
  - deploy

lint_dockerfile:
  stage: lint_dockerfile
  image: registry.gitlab.com/junte/docker-hub/hadolint/hadolint:v1.19.0-44-gf364c91-debian
  script:
    - hadolint Dockerfile

build:
  image: registry.gitlab.com/junte/docker-hub/docker:19
  stage: build
  services:
    - registry.gitlab.com/junte/docker-hub/docker:19-dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $DOCKER_CACHE_IMAGE || true
  script:
    - docker build --cache-from $DOCKER_CACHE_IMAGE -t $DOCKER_CACHE_IMAGE -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
    - docker push $DOCKER_CACHE_IMAGE

deploy:
  image: registry.gitlab.com/junte/docker-hub/curl:7.72.0
  stage: deploy
  dependencies: []
  script:
    - curl -k -X POST -d "component=${DEPLOYER_COMPONENT}&key=${DEPLOYER_KEY}&tag=${CI_PIPELINE_ID}" ${DEPLOYER_HOST}
  environment:
    name: production
    url: $SITE_ADDRESS
